### ISSUE TITLE
Memoria Compatibility

### ISSUE THREAD

**Issue by Albeoris** [KiameV/moogle-mod-manager#19]
Hi!

How can we make your manager compatible with [Memoria](https://github.com/Albeoris/Memoria.FFPR)?

Memoria has a built-in mod loading mechanism that allows you to change individual entries in .csv and .txt files.

**Comment by KiameV** [comment]
If it's more to the end of editing specific csv/txt files, we could
consider find/replace via regex, line number/key, or some other means.
xml/json mod file would specify: file to edit, what to find/how to find,
replace

**Comment by Albeoris** [comment]
Okay, so I don't need to tweak anything on my end?

As far as I can see, now the frameworks - BeepInEx, Memoria and Magicite are chosen by the author of the mod as the installation method.

Seems like BeepInEx, Memoria and Magicite should also be mods, and installed as dependencies when needed.

And here, it seems, some work is needed, since only a specific version can be selected in the list of required mods. And in the case of BeepInEx, Memoria, etc. it is important for us that the version is NOT lower than a certain one. Otherwise, we won't be able to install old mods that don't update dependencies.

What are you thinking about?

**Comment by KiameV** [comment]
Yeah this will need to be thought out more. There is nothing backing
versions atm. When it does become enforced tokens like ">=" or "*" (ie 1.*)
can be considered

**Comment by Albeoris** [comment]
I think any solutions that allow you to specify such a constraint are suitable:
```
Min supported version: 0.9a
Max supported version: 2022.01.01-rc3
```
These can be comparison operators and *, if semicolon enumeration is supported, or regular expressions.

I think we need two options: simple, where you specify:
1.1.*; 2.*; 3.*

And complex, where you can describe any regular expression for corner cases.

**Comment by KiameV** [comment]
I'll need to look into memoria, Magicite, and bepinex more. Right now I am
focused on moving files from a to b.

For memoria would this be enough? Move csv from mod folder to memoria
folder? Before I ask too many questions beyond that let me learn how
memoria works ;)
