### ISSUE TITLE
LoadFromFile returning nil on file not found

### ISSUE THREAD

**Issue by Silvris** [KiameV/moogle-mod-manager#29]
As title states, util.LoadFromFile returns nil by default, which it can only reach when a file does not exist. This should throw an error.

**Comment by Silvris** [comment]
Ah, not exactly that. But still, not throwing an error when os.Stat returns an error will cause the FirstTime config screen to not load.

**Comment by KiameV** [comment]
Doh I was just working on that and never tested the case of no config...

**Comment by KiameV** [comment]
Fixed with v 0.1.3
Thanks!
